### ISSUE TITLE
Can not get Nextion display to show anything from AGC or piDSKY-BS.py

### ISSUE THREAD

**Issue by TheRealGreatOldOne** [bschymanski/DSKY_RaspberryPI_virtualAGC#1]
Hi Bernd,

It’s Jason from the OpenDSKY google groups forum. After a long time thinking about it, I’ve decided to start a new DSKY build with a Pi and a Nextion display. I’ve found your GitHub, and managed to get the Nextion HMI file compiled and onto the display, and the virtual AGC onto the pi.. but then it all seems to come to a halt.

I’m not sure what I’m doing wrong. The display is connected to the Pi via the UART pins, RX to TX and vice versa. I get the ‘blank display’ on start up (no numerals, just the lines, PROG, NOUN & VERB).

I can VNC onto the pi, and start the AGC there and from the command line (once I’d worked out the commands in the README had incorrect directories referenced)

when I start the python script though, nothing happens on the display. It begins running through telling me it’s clearing the display, dimming etc… but the screen just stays the same. No change.

Any help would be appreciated.

Jason

**Comment by TheRealGreatOldOne** [comment]
Here's some pics of what's going on.
![IMG_0841](https://github.com/bschymanski/DSKY_RaspberryPI_virtualAGC/assets/43447047/7445ef18-8a84-4fa5-a11a-7c2c4f046a82)
<img width="1319" alt="piDSKY output" src="https://github.com/bschymanski/DSKY_RaspberryPI_virtualAGC/assets/43447047/48e89220-b76a-4033-9536-598112228959">

**Comment by bschymanski** [comment]
Hi Jason,


Hmmm, there should have happned something on the display.

I am at work right now and cannot Check the cableling on my side. Have you
tried swapping rx and tx?

Cheers

Bernd

TheRealGreatOldOne ***@***.***> schrieb am Mi. 24. Apr. 2024
um 11:01:

**Comment by TheRealGreatOldOne** [comment]
Yeah - I've tried swapping the RX and TX lines and double checked they're on the right GPIO pins. I've also ensured that UART is on in Raspi-Config (no login console, serial port enabled).

ttyS0 is present in /dev as well.

BTW, the correct command line to start the AGC from the command line is:

`/home/pi/VirtualAGC/bin/yaAGC --core="/home/pi/virtualagc/Luminary099/Luminary099.bin" --port=19797 --cfg="/home/pi/VirtualAGC/Resources/LM.ini"`

And if anyone else has issues on start up of the DSKY py script, make sure you have the fan enabled in  Raspi-Config, as the script looks for the fan file in /sys/class and you will also need NTP installing

`sudo apt-get install ntp`

**Comment by bschymanski** [comment]
Hi,

in the piDSKY-bs.py i open the serial Port like this: ser = serial.Serial( port='/dev/ttyS0',baudrate = 9600,timeout=0.1)

Are the Parameters the same for you?

**Comment by TheRealGreatOldOne** [comment]
Yes - but immediatly after the serial open, there's a ser.close command:

`# define some colors for the Indicator Panel
yellow = (100, 70, 0)
red  = (160, 0, 0)
green =  (0, 100, 0)
white = (100, 70, 70)
black = (0, 0, 0)

ser = serial.Serial( port='/dev/ttyS0',baudrate = 9600,timeout=0.1)
ser.close()
k=struct.pack('B', 0xff)
eof = "\xff\xff\xff"
nextion_sleep = 0.05
`

Is there anything else needed on the Nextion display? All I've done there is pull the files from here, fire up the Nextion editor and compile it - followed by a save of the .TFT file. I just stuck that on an SD card and loaded it by power cycling the screen.

**Comment by bschymanski** [comment]
i have to check in the Nextion Editor if the baudrate is independent from the HMI File or not... 
For some reason i suspect that the baudrate is not correct.

**Comment by bschymanski** [comment]
![IMG_4696](https://github.com/bschymanski/DSKY_RaspberryPI_virtualAGC/assets/34037236/9f47f9c5-0b68-42d2-ac88-c439702aa1d8)
i don't have the same Nextion Display a second time, so i cannot replicate your problem. 
But my other nextion Display works with another Raspberry Pi.
If you put your SD Card in the Nextion Display, what Baudrate is shown?

**Comment by bschymanski** [comment]
can you upload this file to your Display: hardware/nextion/nextiondsky.tft
The HMI File is supposed to be used with the Nextion Editor.

**Comment by TheRealGreatOldOne** [comment]
Hi, 

I did some more troubleshooting this morning during a boring conference call... :)

I connected the display via a USB / UART converter rather than direct to the GPIO pins, changed the serial setup line from ttyS0 to ttyUSB0 and voila:

![IMG_0850](https://github.com/bschymanski/DSKY_RaspberryPI_virtualAGC/assets/43447047/a7a6a93d-8eec-4661-8374-7d269d773eaf)

I can on conclude that the UART GPIO pins on this Pi are borked somehow. Not sure how - I've checked that Raspi-gpio spits out what I believe are the correct settings for 14 & 15:

`pi@pithreeb:~/DSKY_RaspberryPI_virtualAGC/Software/RaspberryPi_DSKY $ raspi-gpio get 14,15
GPIO 14: level=0 fsel=4 alt=0 func=TXD0
GPIO 15: level=0 fsel=4 alt=0 func=RXD0
pi@pithreeb:~/DSKY_RaspberryPI_virtualAGC/Software/RaspberryPi_DSKY $ `

Although I have not checked that they are actually electrically active with a scope or anything as yet.

So it's not you, it's me. 😃

**Comment by bschymanski** [comment]
Perfect! Glad it works now!
Keep me updated how your DSKY comes along if you like :-)
